MvcInterface/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using MvcInterface.Models;

namespace MvcInterface.Controllers
{
    public class FilesController : Controller
    {
        //
        // GET: /Files/

        public ActionResult Index()
        {
            var desc = FileWorker.FileName == null? null: new FileDescription{Name = FileWorker.FileName};
        
            return View(desc);
        }

        public ActionResult UploadImage()
        {
            return View();
        }

        [HttpPost]
        //  [ValidateAntiForgeryToken]
        public ActionResult UploadImage(HttpPostedFileBase image)
        {
            //image.SaveAs(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"av1"));
            FileWorker.SaveFile(image);
            return RedirectToAction("Index");
        }

        public ActionResult GetImage()
        {
            return File(FileWorker.GetFile("D:\\myfile"), "image/jpeg", "D:\\myfile");
        }


    }
}

MvcInterface/Views/Files/Index.cshtml
@model MvcInterface.Models.FileDescription

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if (Model == null)
{
    <div>File not loaded</div>
    @Html.ActionLink("UploadImage","UploadImage");
}
else
{
    <div>File @Model.Name loaded</div>
    <img src="@Url.Action("GetImage")" />
}

MvcInterface/Views/Files/UploadImage.cshtml
@{
    ViewBag.Title = "UploadImage";
}

<h2>UploadImage</h2>

@using (Html.BeginForm("UploadImage", "Files", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="image" />
    
     <input type="submit" value="Load"/>
}