MvcInterface/Models/Users.cs
namespace MvcInterface.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    using EpamTask6_1.UserList.Entities;
    using EpamTask6_1.UserList.Logic;

    using MvcInterface.Models;

    public class Users
    {
        public static string DefaultImage = UserImage.DefaultUserImage;

        public static string ImageDirectory= UserImage.UserImageDirectory;

        [HiddenInput(DisplayValue = false)]
        public Guid ID { get; set; }

        [Required(ErrorMessage = "Необходимо ввести имя пользователя!")]
        [Display(Name = "Имя")]
        [Remote("CheckUserName", "Users")]
        public string Name { get; set; }


        //!DATE
        [Required(ErrorMessage = "Необходимо ввести дату рождения пользователя!")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Дата рождения")]
        public DateTime DateOfBirth { get; set; }

        public int Age { get; set; }

        public string ImageAddr { get; set; }
       
        public List<Guid> _awardList = new List<Guid>();

        public List<Awards> _awardNotHasList = new List<Awards>();
        
        public Users() { }

        public Users(string name, DateTime dateOfBirth)
        {
            this.Name = name;
            this.DateOfBirth = dateOfBirth;
            this.ImageAddr = Path.Combine(Users.ImageDirectory, Users.DefaultImage);
        }

        public Users(Guid id, string name, DateTime dateOfBirth, int age)
        {
            this.ID = id;
            this.Name = name;
            this.DateOfBirth = dateOfBirth;
            this.Age = age;
            //this.ImageAddr = DefaultImage;
            this.ImageAddr = Path.Combine(Users.ImageDirectory, Users.DefaultImage);
        }

        public Users(Guid id, string name, DateTime dateOfBirth, int age, IEnumerable<Guid> inputList) :
            this(id, name, dateOfBirth, age)
        {
            this.ID = id;
            this.Name = name;
            this.DateOfBirth = dateOfBirth;
            this._awardList = inputList.ToList();
            this.Age = age;
            //this.ImageAddr = DefaultImage;
            this.ImageAddr = Path.Combine(Users.ImageDirectory, Users.DefaultImage);
        }

        public static IEnumerable<Users> GetAllUsers()
        {
            var list = BusinessLogicHelper._logic.GetAllUsers();
            foreach (var item in list)
            {
                Users user = new Users(item.ID, item.Name, item.DateOfBirth, item.Age, item.GetAwardList());
                if (BusinessLogicHelper._logic.GetUserImage(user.ID))
                {
                    //user.ImageAddr = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "App_Data", "UserImages", user.ID.ToString());
                    user.ImageAddr = Path.Combine(Users.ImageDirectory, user.ID.ToString());
                }
                else
                {
                    //user.ImageAddr = Users.DefaultImage ;
                    user.ImageAddr = Path.Combine(Users.ImageDirectory, DefaultImage);
                }
                yield return user;
            }
        }

        public static Users GetUser(Guid id)
        {
            var item = BusinessLogicHelper._logic.GetUserByID(id);
            Users user = new Users(item.ID, item.Name, item.DateOfBirth, item.Age, item.GetAwardList());

            if (BusinessLogicHelper._logic.GetUserImage(user.ID))
            {
                //user.ImageAddr = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "App_Data", "UserImages", user.ID.ToString());
                user.ImageAddr = Path.Combine(Users.ImageDirectory, user.ID.ToString());
            }
            else
            {
                //user.ImageAddr = Users.DefaultImage ;
                user.ImageAddr = Path.Combine(Users.ImageDirectory, DefaultImage);
            }
            user.GetUserNotHasAwards(user.ID);
            return user;
        }

        public static void CreateUser(Users model)
        {
            BusinessLogicHelper._logic.AddUser(model.Name, model.DateOfBirth);
        }

        public static void DeleteUser(Guid id)
        {
            User nu = BusinessLogicHelper._logic.GetUserByID(id);
            BusinessLogicHelper._logic.DeleteUser(nu);
        }

        public static bool AddAwardToUser(Guid UserID, Guid AwardID)
        {
            User nu = BusinessLogicHelper._logic.GetUserByID(UserID);
            return BusinessLogicHelper._logic.AddAwardToUser(UserID, AwardID);
        }

        public static IEnumerable<Awards> GetUserAwards(Guid id)
        {
            User nu = BusinessLogicHelper._logic.GetUserByID(id);
            var list = BusinessLogicHelper._logic.GetUserAwards(nu);
            foreach (var item in list)
            {
                Awards award = new Awards(item.ID, item.Title);
                if (BusinessLogicHelper._logic.GetAwardImage(award.ID))
                {
                    //award.ImageAddr = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "App_Data", "AwardImages", award.ID.ToString());
                    award.ImageAddr = Path.Combine(Awards.ImageDirectory, award.ID.ToString());
                }
                else
                {
                    //award.ImageAddr = Awards.DefaultImage;
                     award.ImageAddr = Path.Combine(Awards.ImageDirectory, Awards.DefaultImage);
                }
                yield return award;
               
            }
        }

        public void GetUserNotHasAwards(Guid id)
        {
            this._awardNotHasList.Clear();
            User nu = BusinessLogicHelper._logic.GetUserByID(id);
            List<Award> list = BusinessLogicHelper._logic.GetUserAwards(nu).ToList();
            List<Award> all = BusinessLogicHelper._logic.GetAllAwards().ToList();

            if (list.Count() == 0)
            {
                foreach (var item in all)
                {
                    Awards award = new Awards(item.ID, item.Title);
                    if (BusinessLogicHelper._logic.GetAwardImage(award.ID))
                    {
                        award.ImageAddr = Path.Combine(Awards.ImageDirectory, award.ID.ToString());
                    }
                    else
                    {
                        award.ImageAddr = Path.Combine(Awards.ImageDirectory, Awards.DefaultImage);
                    }
                    this._awardNotHasList.Add(award);
                }
            }
            else
            {
                foreach (var item in all)
                {
                    bool contains = false;
                    foreach (var other in list)
                    {
                        if ((item.ID == other.ID))
                        {
                            contains = true;
                        }
                    }

                    if (!contains)
                    {
                        Awards award = new Awards(item.ID, item.Title);
                        if (BusinessLogicHelper._logic.GetAwardImage(award.ID))
                        {
                            award.ImageAddr = Path.Combine(Awards.ImageDirectory, award.ID.ToString());
                        }
                        else
                        {
                            award.ImageAddr = Path.Combine(Awards.ImageDirectory, Awards.DefaultImage);
                        }
                        this._awardNotHasList.Add(award);
                    }
                }

                //???
                //foreach (var item in all)
                //{                    
                //    if (list.Contains(item))
                //    {
                //        all.Remove(item);
                //    }
                //}

                //foreach (var item in all)
                //{
                //    Awards award = new Awards(item.ID, item.Title);
                //    if (BusinessLogicHelper._logic.GetAwardImage(award.ID))
                //    {
                //        award.ImageAddr = Path.Combine(Awards.ImageDirectory, award.ID.ToString());
                //    }
                //    else
                //    {
                //        award.ImageAddr = Path.Combine(Awards.ImageDirectory, Awards.DefaultImage);
                //    }
                //    this._awardNotHasList.Add(award);
                //}
            }            
        }

        public static bool CheckUserName(string username)
        {
            var list = BusinessLogicHelper._logic.GetAllUsers();
            foreach (var user in list)
            {
                if (user.Name == username)
                {
                    return false;
                }
            }
            return true;
        }

        public void SetImage()
        {
            //if (!Users._usersImageList.ContainsKey(this.ID))
            //{
            //    Users._usersImageList.Add(this.ID, Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "App_Data", "UserImages", this.ID.ToString()));
            //    this.ImageAddr = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "App_Data", "UserImages", this.ID.ToString());
            //}
            //else
            //{
            //    Users._usersImageList[this.ID] = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "App_Data", "UserImages", this.ID.ToString());
            //    this.ImageAddr = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "App_Data", "UserImages", this.ID.ToString());
            //}
            BusinessLogicHelper._logic.SetUserImage(this.ID);
            this.ImageAddr = Path.Combine(Users.ImageDirectory, this.ID.ToString());
        }

        public void RemoveImage()
        {

MvcInterface/Controllers/AwardsController.cs
namespace MvcInterface.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    using MvcInterface.Models;
    using System.Web.UI;

    public class AwardsController : Controller
    {
        //
        // GET: /Awards/
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var model = Awards.GetAllAwards();
            return View(model);
        }

        //
        // GET: /Awards/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Awards/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(Awards model)
        {
            if (ModelState.IsValid)
            {
                Awards.CreateAward(model);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public JsonResult CheckAwardTitle(string Title)
        {
            var result = Awards.CheckAwardTitle(Title);

            if (result)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("Award with this Title already exists.", JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetAwardImage(string path)
        {
            return File(FileWorker.GetFile(path), "image/jpeg", path);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult UploadImage(Guid id)
        {
            Guid AwardID = id;
            return View(AwardID);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult UploadImage(Guid id, HttpPostedFileBase image)
        {
            Guid AwardID = id;
            try
            {
                Awards award = Awards.GetAward(id);
                string path = Path.Combine(Awards.ImageDirectory, award.ID.ToString());
                FileWorker.SaveFile(image, path);
                award.SetImage();
            }
            catch
            {  
                return RedirectToAction("Index");
            }
            
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult RemoveImage(Guid id)
        {
            Awards award = Awards.GetAward(id);
            award.RemoveImage();
            Guid AwardID = id;
            return RedirectToAction("Index");            
        }
    }
}

MvcInterface/Controllers/UsersController.cs
namespace MvcInterface.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    using MvcInterface.Models;
    using System.Web.UI;

    public class UsersController : Controller
    {
        //
        // GET: /Users/
        // watch all users
        [AllowAnonymous]
        public ActionResult Index()
        {
            var model = Users.GetAllUsers();
            return View(model);
        }

        [Authorize(Roles="User, Admin")]
        public ActionResult Details(Guid id)
        {
            var model = Users.GetUser(id);
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(Users model)
        {
            if (ModelState.IsValid)
            {
                Users.CreateUser(model);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public JsonResult CheckUserName(string Name)
        {
            var result = Users.CheckUserName(Name);

            if (result)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("User with this name already exists.", JsonRequestBehavior.AllowGet);
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(Guid id)
        {
            var model = Users.GetUser(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(Users model)
        {
            try
            {
                Users.DeleteUser(model.ID);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        [Authorize(Roles = "User, Admin")]
        public ActionResult UserAwards(Guid id)
        {
            var model = Users.GetUser(id);
            return View(model);
        }

        //[ChildActionOnly]
        [Authorize(Roles = "User, Admin")]
        public ActionResult GetUserAwards(Guid id)
        {
            var model = Users.GetUserAwards(id);
            return PartialView(model);
        }

        [Authorize(Roles = "User, Admin")]
        public ActionResult GetUserAwardsToIndex(Guid id)
        {
            var model = Users.GetUserAwards(id);
            return PartialView(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddAwardToUser(Guid id)
        {
            var model = Users.GetUser(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult AddAwardToUser(Guid UserID, Guid AwardID)
        {
            var model = Users.GetUser(UserID);
            if (Users.AddAwardToUser(UserID, AwardID))
            {
                return RedirectToAction("UserAwards", new { id = UserID });
            }
            else
            {
                return View(model);
            }
        }

        public ActionResult GetUserImage(string path)
        {
            return File(FileWorker.GetFile(path), "image/jpeg", path);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult UploadImage(Guid id)
        {
            Guid UserID = id;
            return View(UserID);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult UploadImage(Guid id, HttpPostedFileBase image)
        {
            Guid UserID = id;
            try
            {
                Users user = Users.GetUser(id);
                string path = Path.Combine(Users.ImageDirectory, user.ID.ToString());
                FileWorker.SaveFile(image, path);
                user.SetImage();
            }
            catch
            {
                return RedirectToAction("Details", new { id = UserID });
            }

            return RedirectToAction("Details", new { id = UserID });
        }

        //  [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult RemoveImage(Guid id)
        {
             Users user = Users.GetUser(id);
             user.RemoveImage();
             Guid UserID = id;

             return RedirectToAction("Details", new { id = UserID });
        }

    }
}

MvcInterface/Views/Users/AddAwardToUser.cshtml
@model MvcInterface.Models.Users

@{
    ViewBag.Title = "AddAwardToUser";
    var list = Model._awardNotHasList;
}

<h2>AddAwardToUser</h2>


@foreach (var item in list) {

    @*    @Html.DisplayFor(modelItem => item.Title) |
        @Html.ActionLink("Add", "AddAwardToUser", new { AwardID=item.ID }) *@

        
        using (Html.BeginForm())
        {
            @Html.ValidationSummary(true)
            <fieldset>       
                <legend></legend>
                
            <div class="row-fluid show-grid">

                <div class="span1" >
                     <img src="@Url.Action("GetAwardImage", "Awards", new { path = item.ImageAddr })" class="img-thumbnail" />
                </div>
                <div class="span1" ></div>
                <div class="span2" ></div>
                <div class="span4" ></div>
                <div class="span4" ></div>

            </div>
         

                <div class="editor-field">
                 @Html.DisplayFor(modelItem => item.Title)
                </div>

                @Html.Hidden("UserID", Model.ID)
                @Html.Hidden("AwardID", item.ID)
                @Html.AntiForgeryToken()
                <p>
                    <input type="submit" value="Add" />
                </p>
            </fieldset>
        }          
}

<div>
    @Html.ActionLink("Back to Details", "Details", new { id=Model.ID })
</div>

MvcInterface/Views/Users/Create.cshtml
@model MvcInterface.Models.Users

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@*<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>*@

@*<script src="@Url.Content("~/Scripts/jquery-ui-1.10.4.min.js")" type="text/javascript"></script>
<script src="../../Scripts/bootstrap.min.js"></script>
<script src="../../Scripts/bootstrap-datepicker.js"></script>*@


@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>User</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateOfBirth)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.DateOfBirth, new { @class = "date" })
            @Html.ValidationMessageFor(model => model.DateOfBirth)


        </div>
        @Html.AntiForgeryToken()
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts {

    @*<script src="~/Scripts/jquery-ui-1.10.4.min.js"></script>*@
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    
    <script type="text/javascript">
        $(document).ready(function () {
            $('.date').datepicker({ firstDay: 1, dateFormat: 'dd.mm.yy' });
        });
    </script>
}

MvcInterface/Views/Users/Delete.cshtml
@model MvcInterface.Models.Users

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>User</legend>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">DateOfBirth</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateOfBirth)
    </div>

    <div class="display-label">Age</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Age)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        @Html.AntiForgeryToken()
        <input type="submit" value="Delete" /> 
       
    </p>
}


<div>
    @Html.ActionLink("Back to Details", "Details", new { id=Model })
</div>
<p>
 @Html.ActionLink("Back to List", "Index")
 </p>

MvcInterface/Views/Users/Details.cshtml
@model MvcInterface.Models.Users

@{
    ViewBag.Title = "Details";
   // string imageurl = Model.ImageAddr;
}

<h2>Details</h2>

<div class="row-fluid show-grid">

    <div class="span1" >
         <img src="@Url.Action("GetUserImage", new { path = Model.ImageAddr })" class="img-details"/>
    </div>
    <div class="span1" ></div>
    <div class="span2" ></div>
    <div class="span4" ></div>
    <div class="span4" ></div>

</div>

<table class="table">
    <tr>

        <th>
            Name
        </th>
        <th>
            Date of Birth
        </th>
        <th>
            Age
        </th>
        <th></th>
    </tr>

    <tr>
        <td>
            @Html.DisplayFor(model => model.Name)
        </td>
        <td>
            @Html.DisplayFor(model => model.DateOfBirth)
        </td>
        <td>
            @Html.DisplayFor(model => model.Age)
        </td>
        <td>

            @Html.ActionLink("Awards", "UserAwards", new { id = Model.ID })  

            @if (User.IsInRole("Admin") )
            {
                <div >@Html.ActionLink("Add new Award", "AddAwardToUser", new { id = Model.ID })  </div>
                <div >@Html.ActionLink("Change Image", "UploadImage", new { id = Model.ID }) </div>
                <div >@Html.ActionLink("Remove Image", "RemoveImage", new { id = Model.ID }) </div>
                <div >@Html.ActionLink("Delete", "Delete", new { id = Model.ID })   </div>   
                 
            }                 
        </td>
    </tr>

</table>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcInterface/Views/Users/Edit.cshtml
@model MvcInterface.Models.Users

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>User</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateOfBirth)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateOfBirth)
            @Html.ValidationMessageFor(model => model.DateOfBirth)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcInterface/Views/Users/GetUserAwards.cshtml
@model IEnumerable<MvcInterface.Models.Awards>

@if (Model.Count()==0)
{
    
    @:У данного пользователя пока нет наград
    
}
else
{
    <table class="table">
        <tr>
            <th></th>
            <th>
                Title
            </th>        
        </tr>

    @foreach (var item in Model) {
        <tr>
             <td>
            <div class="row-fluid show-grid">

                <div class="span1" >
                     <img src="@Url.Action("GetAwardImage", "Awards", new { path = item.ImageAddr })" class="img-thumbnail" />
                </div>
                <div class="span1" ></div>
                <div class="span2" ></div>
                <div class="span4" ></div>
                <div class="span4" ></div>

            </div>
         </td>

            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>      
        </tr>
    }

    </table>
}

MvcInterface/Views/Users/GetUserAwardsToIndex.cshtml
@model IEnumerable<MvcInterface.Models.Awards>

@if (Model.Count()==0)
{
    
    @:This user has no awards yet
    
}
else
{
    <table class="table">
     
        <tr>
             @foreach (var item in Model) {
            <th> @Html.DisplayFor(modelItem => item.Title)</th>  
             }       
        </tr>
        
        <tr>
        @foreach (var item in Model) {
        
            <td>
            <div class="row-fluid show-grid">
                <div class="span1" >
                     <img src="@Url.Action("GetAwardImage", "Awards", new { path = item.ImageAddr })" class="img-thumbnail" />
                </div>
                <div class="span1" ></div>
                <div class="span2" ></div>
                <div class="span4" ></div>
                <div class="span4" ></div>
            </div>
            </td>
        }
        </tr>
    
    </table>
}

MvcInterface/Views/Users/Index.cshtml
@model IEnumerable<MvcInterface.Models.Users>

@{
    ViewBag.Title = "Users";    
}

<h2>Users</h2>
@if (User.IsInRole("Admin") )
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}    

<table class="table">
    <tr>
        <th></th>

        <th>
            Name
        </th>

        <th></th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    var awList = item._awardList;
    <tr>
         <td>
            <div class="row-fluid show-grid">

                <div class="span1" >
                     <img src="@Url.Action("GetUserImage", new { path = item.ImageAddr })" class="img-thumbnail" />
                </div>
                <div class="span1" ></div>
                <div class="span2" ></div>
                <div class="span4" ></div>
                <div class="span4" ></div>

            </div>
         </td>

        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>

        @if (User.IsInRole("Admin") || User.IsInRole("User"))
        {
            <td>
               @Html.ActionLink("Details", "Details", new { id=item.ID }) 
            </td>
            
            <td>
                @Html.Action("GetUserAwardsToIndex", "Users", new { id=item.ID })
            </td>
        }
    </tr>
}

</table>    

MvcInterface/Views/Users/UploadImage.cshtml
@model System.Guid

@{
    ViewBag.Title = "UploadImage";
    
}

<h2>Upload Image</h2>

@using (Html.BeginForm("UploadImage", "Users", FormMethod.Post, new { enctype = "multipart/form-data", id = Model}))
{
    @Html.AntiForgeryToken()
  
    <table class ="table">
    <tr>
        <th>
            <input  type="file" name="image" />   
        </th> 
    </tr>
    
    <tr>
        <td>
        <input type="submit" value="Load file"/>
        </td>
    </tr>
    </table>


}

<div>
    @Html.ActionLink("Back to Details", "Details", new { id=Model })
</div>

MvcInterface/Views/Users/UserAwards.cshtml
@model MvcInterface.Models.Users

@{
    ViewBag.Title = "UserAwards";
}

<h2>UserAwards</h2>

@Html.Action("GetUserAwards", Model.ID)

<div>
    @Html.ActionLink("Back to Details", "Details", new { id=Model.ID })
</div>